name: Build README
on:
  push:
    branches:
    - main
    paths-ignore:
    - README.md
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
      with:
        # necessary for github-action-til-autoformat-readme
        fetch-depth: 0
    - name: Autoformat README
      uses: cflynn07/github-action-til-autoformat-readme@1.2.0
      with:
        description: |
          **A good memory does not eqaul pale ink.**
        #footer: |
  
        #list_most_recent: 2 # optional, lists most recent TILS below description
        #date_format: "" # optional, must align to https://golang.org/pkg/time/#Time.Format
