name: Update README with recent posts

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight every day

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch recent posts
        run: |
          # Use curl to fetch recent posts from your blog or website
          # Parse the response data and generate a Markdown list
          echo "- Post 1\n- Post 2\n- Post 3" > recent-posts.md
      - name: Update README file
        run: |
          # Replace placeholder text in README file with generated Markdown list
          sed -i 's/RECENT_POSTS_PLACEHOLDER/$(cat recent-posts.md)/' README.md
      - name: Commit and push changes
        uses: actions/checkout@v2
        run: |
          git config --global user.name "ez-neurai"
          git config --global user.email "ssh3543@gmail.com"
          git add README.md
          git commit -m "Update README with recent posts"
          git push
